#在下面添加你自己的规则链接
https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-hosts.txt
https://raw.githubusercontent.com/lingeringsound/10007_auto/master/all
https://raw.githubusercontent.com/samyansan/AdHosts/master/hosts
https://raw.githubusercontent.com/qq5460168/AD886/main/hosts.txt
https://raw.githubusercontent.com/2Gardon/SM-Ad-FuckU-hosts/refs/heads/master/SMAdHosts
https://raw.githubusercontent.com/maxiaof/github-hosts/master/hosts