# 一行一个你希望从订阅规则里放行的域名 '#'开头为注释行。
#牛头白名单，和微信QQ的白名单
api.jsonsilo.com
dns.weixin.qq.com.cn
dns.weixin.qq.com
dns.weixin.qq.cn
ad.weixin.qq.com
badjs.weixinbridge.com
configv2.unityads.unitychina.cn
googleads.g.doubleclick.net
dl.google.com
accounts.google.com